name: dclanebus
base: core22 # the base snap is the execution environment for this snap
version: '0.2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: sample dbus client/server apps in python
description: |
    just for learning
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:

  dclanebus:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/dclane-code/dbus-demo.git
    stage-packages: [python3-dasbus]

    ## -- local testing --
    # plugin: dump
    # source: .
    organize:
      dclanebus.conf: etc/dclanebus.conf

apps:
  client:
    command: dclanebus_client.py
    extensions: [gnome]
    environment: 
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
  server:
    command: dclanebus_server.py
    extensions: [gnome]
    environment: 
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
  conf:
    command: dclanebus_conf.py

layout:
  /etc/dclanebus.conf:
    bind-file: $SNAP/etc/dclanebus.conf
    
#    prime:
#      - usr/lib/python3/dist-packages/dasbus
#    build-packages:
#     - python3-dasbus
#     - libglib2.0-dev
#     - libglib2.0-0
#     - libgirepository-1.0-1
#     - libffi8
#     - gir1.2-glib-2.0
#    stage-packages:
#     - python3-dasbus
#    - libgirepository-1.0-1
#     - gir1.2-glib-2.0
#     - libffi8
#     - libglib2.0-dev
#     - libglib2.0-0
#     - libgtk2.0-0

##  dasbus:
#    plugin: python
#    python-packages:
#      - dasbus
#    override-build: |           #maybe try taking this out
#      snapcraftctl build
#      pip3 install wheel
#      pip3 install pycairo
#      pip3 install PyGObject
#    build-packages:
#      - pkg-config
#      - libcairo2-dev       
#      - libgirepository1.0-dev
#    stage-packages:
#      - libcairo-gobject2
#      - libcairo2
#      - libfontconfig1
#      - libfreetype6
#      - libgirepository-1.0-1
#      - libpixman-1-0
#      - libpng16-16
#      - libx11-6
#      - libxau6
#      - libxcb-render0
#      - libxcb-shm0
#      - libxcb1
#      - libxdmcp6
#      - libxext6
#      - libxrender1
#      - gir1.2-glib-2.0
#      - libglib2.0-dev
#      - libglib2.0-0
#      - python3-gi
#      - python3-dasbus
#

#layout:
#  /usr/lib/python3/dist-packages/dasbus:
#    bind: $SNAP/usr/lib/python3/dist-packages/dasbus
#  /usr/lib/python3/dist-packages/gi:
#    bind: $SNAP/usr/lib/python3/dist-packages/gi
#  /usr/lib/python3/dist-packages/pygtkcompat:
#    bind: $SNAP/usr/lib/python3/dist-packages/pygtkcompat


