name: dclanebus
base: core22 # the base snap is the execution environment for this snap
version: '0.3.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: sample snap things
description: |
    just for learning
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:

  dclanebus:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://github.com/dclane-code/dbus-demo.git
    stage-packages: [python3-dasbus]

    ## -- local testing --
    # plugin: dump
    # source: .
    organize:
      dclanebus.conf: etc/dclanebus.conf

  dcl_echo:
    plugin: make
    source: .


slots:
  dclanebus-server:
    interface: dbus
    bus: system             # has to be a system bus because its a daemon
    name: org.dclane.Dave

plugs:
  dclanebus-client:
    bus: system
    interface: dbus
    name: org.dclane.Dave

apps:

  client:
    command: dclanebus_client.py
    extensions: [gnome]
    environment: 
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs: [ dclanebus-client ]

  server:
    command: dclanebus_server.py
    daemon: simple
    slots: [ dclanebus-server ]
    extensions: [gnome]
    environment: 
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
  conf:
    command: dclanebus_conf.py

  unixecho:
    command: dcl_echo_srv
    plugs:
    - network-bind

  unixecho_abstract:
    command: dcl_echo_srv_abs
    plugs:
    - network-bind

layout:
  /etc/dclanebus.conf:
    bind-file: $SNAP_COMMON/etc/dclanebus.conf
    
